apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ssd-storage
provisioner: ssd-provisioner
parameters:
  archiveOnDelete: "true"
  pathPattern: "${.PVC.annotations.nfs.io/storage-path}"
