apiVersion: v1
kind: Service
metadata:
  name: aliyundrive-webdav
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: aliyundrive-webdav
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aliyundrive-webdav
spec:
  selector:
    matchLabels:
      app: aliyundrive-webdav
  serviceName: aliyundrive-webdav
  replicas: 1
  template:
    metadata:
      labels:
        app: aliyundrive-webdav
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: aliyundrive-webdav
          image: messense/aliyundrive-webdav:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: REFRESH_TOKEN
              value: abc123
            - name: WEBDAV_AUTH_USER
              value: admin
            - name: WEBDAV_AUTH_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: k8s
              subPath: aliyundrive-webdav/config
              mountPath: /etc/aliyundrive-webdav
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
