apiVersion: v1
kind: Service
metadata:
  name: bilibili-helper
spec:
  clusterIP: None
  selector:
    app: bilibili-helper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bilibili-helper
spec:
  selector:
    matchLabels:
      app: bilibili-helper
  serviceName: bilibili-helper
  replicas: 1
  template:
    metadata:
      labels:
        app: bilibili-helper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bilibili-helper
          image: superng6/bilibili-helper:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Asia/Shanghai
            - name: CRON
              value: "true"
          volumeMounts:
            - name: k8s
              subPath: bilibili-helper/config
              mountPath: /config
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
