apiVersion: v1
kind: Service
metadata:
  name: duplicati
spec:
  ports:
    - port: 80
      targetPort: 8200
  selector:
    app: duplicati
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duplicati
spec:
  selector:
    matchLabels:
      app: duplicati
  serviceName: duplicati
  replicas: 1
  template:
    metadata:
      labels:
        app: duplicati
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: duplicati
          image: lscr.io/linuxserver/duplicati:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: k8s
              subPath: duplicati/config
              mountPath: /config
            - name: work
              mountPath: /mnt/work
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: work
          hostPath:
            path: /mnt/work