apiVersion: v1
kind: Service
metadata:
  name: live-rtmp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: web
    - port: 1935
      targetPort: 1935
      nodePort: 30002
      protocol: TCP
      name: rtmp
  selector:
    app: live-rtmp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: live-rtmp
spec:
  selector:
    matchLabels:
      app: live-rtmp
  serviceName: live-rtmp
  replicas: 1
  template:
    metadata:
      labels:
        app: live-rtmp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: live-rtmp
          image: 7yhong/nginx-rtmp:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          ports:
            - containerPort: 8080
            - containerPort: 1935
          volumeMounts:
            - name: k8s
              subPath: live/rtmp/nginx.conf
              mountPath: /etc/nginx/nginx.conf
            - name: k8s
              subPath: live/rtmp/html
              mountPath: /usr/local/nginx/html
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
