apiVersion: v1
kind: Service
metadata:
  name: tinymediamanager
spec:
  ports:
    - port: 80
      targetPort: 5800
  selector:
    app: tinymediamanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tinymediamanager
spec:
  selector:
    matchLabels:
      app: tinymediamanager
  serviceName: tinymediamanager
  replicas: 1
  template:
    metadata:
      labels:
        app: tinymediamanager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: tinymediamanager
          image: romancin/tinymediamanager:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: TZ
              value: Aisa/Shanghai
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ENABLE_CJK_FONT
              value: "1"
            - name: KEEP_APP_RUNNING
              value: "1"
          ports:
            - containerPort: 5800
          volumeMounts:
            - name: k8s
              subPath: tinymediamanager/config
              mountPath: /config
            - name: data
              subPath: media
              mountPath: /media
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: data
          hostPath:
            path: /mnt/data
