apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: lc91926@gmail.com
    privateKeySecretRef:
      name: cloudflare-apikey-secret
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: lc91926@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
