apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lvlv.fun
  namespace: default
spec:
  secretName: lvlv.fun-tls
  issuerRef:
    name: cloudflare-issuer
  dnsNames:
    - "*.lvlv.fun"
