apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  serviceName: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.16.3
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          # env:
          #   - name: ES_JAVA_OPTS
          #     value: "-Xms1024m -Xmx8192m"
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: config
              subPath: kibana.yml
              mountPath: /usr/share/kibana/config/kibana.yml
      volumes:
        - name: config
          configMap:
            name: kibana-config
