apiVersion: v1
kind: Service
metadata:
  name: pan-index
spec:
  ports:
    - port: 80
      targetPort: 5238
  selector:
    app: pan-index
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pan-index
spec:
  selector:
    matchLabels:
      app: pan-index
  serviceName: pan-index
  replicas: 1
  template:
    metadata:
      labels:
        app: pan-index
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pan-index
          image: iicm/pan-index:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: PORT
              value: "5238"
          ports:
            - containerPort: 5238
          volumeMounts:
            - name: k8s
              subPath: pan-index/config
              mountPath: /app/data
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
