apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
    - port: 80
      targetPort: 8080
    - port: 80
      targetPort: 8080
    - port: 80
      targetPort: 8080
  selector:
    app: qbittorrent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  serviceName: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: TZ
              value: Aisa/Shanghai
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: k8s
              subPath: qbittorrent/config
              mountPath: /config
            - name: data
              subPath: media/tv
              mountPath: /tv
            - name: store
              subPath: download
              mountPath: /downloads
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: data
          hostPath:
            path: /mnt/data
        - name: store
          hostPath:
            path: /mnt/store
