apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
    - port: 80
      targetPort: 8096
  selector:
    app: jellyfin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 6
              memory: 8Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: TZ
              value: Aisa/Shanghai
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: k8s
              subPath: jellyfin/config
              mountPath: /config
            - name: k8s
              subPath: jellyfin/font
              mountPath: /data/font
              readOnly: true
            - name: data
              subPath: media
              mountPath: /data/media
              readOnly: true
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: data
          hostPath:
            path: /mnt/data
