apiVersion: v1
kind: Service
metadata:
  name: speedtest-x
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: speedtest-x
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: speedtest-x
spec:
  selector:
    matchLabels:
      app: speedtest-x
  serviceName: speedtest-x
  replicas: 1
  template:
    metadata:
      labels:
        app: speedtest-x
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: speedtest-x
          image: badapple9/speedtest-x:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: MAX_LOG_COUNT
              value: "100"
            - name: IP_SERVICE
              value: "ip.sb"
            - name: SAME_IP_MULTI_LOGS
              value: "true"
          ports:
            - containerPort: 80
