apiVersion: v1
kind: Service
metadata:
  name: meshcommander
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: meshcommander
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meshcommander
spec:
  selector:
    matchLabels:
      app: meshcommander
  serviceName: meshcommander
  replicas: 1
  template:
    metadata:
      labels:
        app: meshcommander
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: meshcommander
          image: node:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 0.1
              memory: 100Mi
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: k8s
              subPath: meshcommander/node
              mountPath: /meshcommander
          command: ["/bin/sh", "-c", "--"]
          args: [
              "
              cd /meshcommander/node_modules/meshcommander;
              node meshcommander --any
              ",
            ]
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
