apiVersion: v1
kind: Service
metadata:
  name: zfile
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: zfile
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zfile
spec:
  selector:
    matchLabels:
      app: zfile
  serviceName: zfile
  replicas: 1
  template:
    metadata:
      labels:
        app: zfile
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zfile
          image: zhaojun1998/zfile:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: k8s
              subPath: zfile/data
              mountPath: /root/.zfile
            - name: data
              mountPath: /mnt/data
              readOnly: true
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: data
          hostPath:
            path: /mnt/data
