apiVersion: v1
kind: Service
metadata:
  name: emby
spec:
  ports:
    - port: 80
      targetPort: 8096
  selector:
    app: emby
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emby
spec:
  selector:
    matchLabels:
      app: emby
  serviceName: emby
  replicas: 1
  template:
    metadata:
      labels:
        app: emby
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: emby
          image: lscr.io/linuxserver/emby:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 6
              memory: 8Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          env:
            - name: TZ
              value: Aisa/Shanghai
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: k8s
              subPath: emby/config
              mountPath: /config
            - name: data
              subPath: media
              mountPath: /data/media
              readOnly: true
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
        - name: data
          hostPath:
            path: /mnt/data
