apiVersion: v1
kind: Service
metadata:
  name: live-srs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: web
    - port: 1935
      targetPort: 1935
      nodePort: 30003
      protocol: TCP
      name: rtmp
    - port: 1985
      targetPort: 1985
      name: web-api
  selector:
    app: live-srs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: live-srs
spec:
  selector:
    matchLabels:
      app: live-srs
  serviceName: live-srs
  replicas: 1
  template:
    metadata:
      labels:
        app: live-srs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: live-srs
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          ports:
            - containerPort: 8080
            - containerPort: 1935
            - containerPort: 1985
          volumeMounts:
            - name: k8s
              subPath: live/srs/conf
              mountPath: /usr/local/srs/conf
          command: ["/bin/sh", "-c", "--"]
          args: [
              "
              ./objs/srs -c conf/docker.conf;
              ",
            ]
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/work/k8s
