apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  serviceName: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: whoami
          image: traefik/whoami:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          ports:
            - containerPort: 80
