apiVersion: v1
kind: Service
metadata:
  name: jd-jdx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: jd-jdx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jd-jdx
spec:
  selector:
    matchLabels:
      app: jd-jdx
  serviceName: jd-jdx
  replicas: 1
  template:
    metadata:
      labels:
        app: jd-jdx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: jd-jdx
          image: registry.cn-hangzhou.aliyuncs.com/yiidii-hub/jdx:v0.2.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 200Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: k8s
              subPath: jd-jdx/config
              mountPath: /jdx/config
      volumes:
        - name: k8s
          hostPath:
            path: /mnt/data/k8s
