apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:5.0.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis
              subPath: data
              mountPath: /redis/data
            - name: redis
              subPath: redis.log
              mountPath: /redis/redis.log
            - name: config
              subPath: redis.conf
              mountPath: /redis/redis.conf
          command:
            - redis-server
            - /redis/redis.conf
      volumes:
        - name: redis
          hostPath:
            path: /mnt/data/k8s/redis
        - name: config
          configMap:
            name: redis-config
